/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: KnightInTheVillage.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @KnightInTheVillage: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("playersMissionIsComplete", () => this.@playersMissionIsComplete, val => this.@playersMissionIsComplete = val);
			VarDef("Score", () => this.@Score, val => this.@Score = val);
			VarDef("KillRobber", () => this.@KillRobber, val => this.@KillRobber = val);
		}

		public StoryVar @playersMissionIsComplete;
		public StoryVar @Score;
		public StoryVar @KillRobber;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@KnightInTheVillage()
	{
		this.StartPassage = "Ask for help";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Ask for help

	void passage1_Init()
	{
		this.Passages[@"Ask for help"] = new StoryPassage(@"Ask for help", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Officer officer please help!!!");
		yield return lineBreak();
		yield return link("Calm down, what happened?", "Tell what happened", null);
		yield return lineBreak();
		yield return link("I can't help I'm busy ", "Leave the farmer", null);
		yield return lineBreak();
		Vars.playersMissionIsComplete  = false;
		yield return lineBreak();
		Vars.Score  = 0;
		yield break;
	}


	// .............
	// #2: Tell what happened

	void passage2_Init()
	{
		this.Passages[@"Tell what happened"] = new StoryPassage(@"Tell what happened", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("He came in the middle of the night, a robber, he stole all my money and no penny left, can you help me?");
		yield return lineBreak();
		yield return link("Give me all the details", "Details", null);
		yield return lineBreak();
		yield return link("Ok I will help you", "Help the farmer", null);
		yield return lineBreak();
		yield return link("I don't want to help you, bye", "Beg the officer", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Beg the officer

	void passage3_Init()
	{
		this.Passages[@"Beg the officer"] = new StoryPassage(@"Beg the officer", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Please he stole everything! I was left with nothing and I'm going to die.");
		yield return lineBreak();
		yield return link("Give me all the details", "Details", null);
		yield return lineBreak();
		yield return link("Ok I will help you", "Help the farmer", null);
		yield return lineBreak();
		yield return link("I can't help you sorry, bye", "Leave the farmer", null);
		yield break;
	}


	// .............
	// #4: Leave the farmer

	void passage4_Init()
	{
		this.Passages[@"Leave the farmer"] = new StoryPassage(@"Leave the farmer", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("You're a terrible person.");
		yield break;
	}


	// .............
	// #5: Help the farmer

	void passage5_Init()
	{
		this.Passages[@"Help the farmer"] = new StoryPassage(@"Help the farmer", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Oh thank you! Bless you");
		yield return lineBreak();
		if(Vars.playersMissionIsComplete == false) {
			yield return lineBreak();
			yield return text("	");
			yield return link("Talk to farmer", "Talk to farmer", null);
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	");
			yield return link("Mission Completed", "Mission Completed", null);
			yield return text(" ");
			yield return lineBreak();
		}
		yield break;
	}


	// .............
	// #6: Talk to farmer

	void passage6_Init()
	{
		this.Passages[@"Talk to farmer"] = new StoryPassage(@"Talk to farmer", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Hello, did you find the robber?");
		yield return lineBreak();
		if(Vars.playersMissionIsComplete == false) {
			yield return lineBreak();
			yield return text("	");
			yield return link("Not yet", "Talk to farmer", null);
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	");
			yield return link("Mission Completed", "Mission Completed", null);
			yield return lineBreak();
		}
		yield break;
	}


	// .............
	// #7: Mission Completed

	void passage7_Init()
	{
		this.Passages[@"Mission Completed"] = new StoryPassage(@"Mission Completed", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Thank you! You are the best, here take some gold!");
		yield return lineBreak();
		Vars.Score  = Vars.Score-400;
		yield break;
	}


	// .............
	// #8: Details

	void passage8_Init()
	{
		this.Passages[@"Details"] = new StoryPassage(@"Details", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Which details whould you like to know?");
		yield return lineBreak();
		yield return link("When did he came?", "Time Details", null);
		yield return lineBreak();
		yield return link("What did he took?", "Gold Details", null);
		yield return lineBreak();
		yield return link("Which way he fled?", "Direction Details", null);
		yield return lineBreak();
		yield return link("What he looked like?", "Look Details", null);
		yield break;
	}


	// .............
	// #9: Time Details

	void passage9_Init()
	{
		this.Passages[@"Time Details"] = new StoryPassage(@"Time Details", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("He arrived in the middle of the night around midnight.");
		yield return lineBreak();
		yield return link("Give me more details", "Details", null);
		yield return lineBreak();
		yield return link("Ok I will help you", "Help the farmer", null);
		yield return lineBreak();
		yield return link("He sounds dangerous, I can't help you ", "Leave the farmer", null);
		yield break;
	}


	// .............
	// #10: Gold Details

	void passage10_Init()
	{
		this.Passages[@"Gold Details"] = new StoryPassage(@"Gold Details", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("He took all my money, 500 gold.");
		yield return lineBreak();
		yield return link("Give me more details", "Details", null);
		yield return lineBreak();
		yield return link("Ok I will help you", "Help the farmer", null);
		yield return lineBreak();
		yield return link("He sounds dangerous, I can't help you ", "Leave the farmer", null);
		yield break;
	}


	// .............
	// #11: Direction Details

	void passage11_Init()
	{
		this.Passages[@"Direction Details"] = new StoryPassage(@"Direction Details", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("He fled to the forest behind you.");
		yield return lineBreak();
		yield return link("Give me more details", "Details", null);
		yield return lineBreak();
		yield return link("Ok I will help you", "Help the farmer", null);
		yield return lineBreak();
		yield return link("He sounds dangerous, I can't help you ", "Leave the farmer", null);
		yield break;
	}


	// .............
	// #12: Look Details

	void passage12_Init()
	{
		this.Passages[@"Look Details"] = new StoryPassage(@"Look Details", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("He was wearing black clothes and a mask so I didn't see his face.");
		yield return lineBreak();
		yield return link("Give me more details", "Details", null);
		yield return lineBreak();
		yield return link("Ok I will help you", "Help the farmer", null);
		yield return lineBreak();
		yield return link("He sounds dangerous, I can't help you ", "Leave the farmer", null);
		yield break;
	}


	// .............
	// #13: Talk to Robber

	void passage13_Init()
	{
		this.Passages[@"Talk to Robber"] = new StoryPassage(@"Talk to Robber", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Can I help you?");
		yield return lineBreak();
		yield return link("Have you seen a suspicious person around?", "Lie", null);
		yield return lineBreak();
		yield return link("You look like a robber", "Deny", null);
		yield break;
	}


	// .............
	// #14: Lie

	void passage14_Init()
	{
		this.Passages[@"Lie"] = new StoryPassage(@"Lie", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Yes, I saw someone suspicious a few hours ago.");
		yield return lineBreak();
		yield return link("You look suspicious", "Deny", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #15: Deny

	void passage15_Init()
	{
		this.Passages[@"Deny"] = new StoryPassage(@"Deny", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("It's not me, I'm an innocent and kind person.");
		yield return lineBreak();
		yield return link("where were you last night?", "Robber Location", null);
		yield return lineBreak();
		yield return link("Why are you dressed like that?", "Robber Clothes", null);
		yield return lineBreak();
		yield return link("You are the robber!!!", "Find Robber", null);
		yield break;
	}


	// .............
	// #16: Robber Location

	void passage16_Init()
	{
		this.Passages[@"Robber Location"] = new StoryPassage(@"Robber Location", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("In my house");
		yield return lineBreak();
		yield return link("Are you sure?", "Deny", null);
		yield break;
	}


	// .............
	// #17: Robber Clothes

	void passage17_Init()
	{
		this.Passages[@"Robber Clothes"] = new StoryPassage(@"Robber Clothes", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("This is my style.");
		yield return lineBreak();
		yield return link("Are you sure?", "Deny", null);
		yield break;
	}


	// .............
	// #18: Find Robber

	void passage18_Init()
	{
		this.Passages[@"Find Robber"] = new StoryPassage(@"Find Robber", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("Okay, you're right. I'm the robber.");
		yield return lineBreak();
		yield return link("I'm going to kill you", "Kill", null);
		yield return lineBreak();
		yield return link("Give me all the stolen money", "Sorry", null);
		yield break;
	}


	// .............
	// #19: Kill

	void passage19_Init()
	{
		this.Passages[@"Kill"] = new StoryPassage(@"Kill", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("No...!!!!");
		yield return lineBreak();
		Vars.KillRobber  = true;
		yield return lineBreak();
		Vars.playersMissionIsComplete  = true;
		yield return lineBreak();
		Vars.Score  = Vars.Score+500;
		yield break;
	}


	// .............
	// #20: Sorry

	void passage20_Init()
	{
		this.Passages[@"Sorry"] = new StoryPassage(@"Sorry", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Here...take back the money I'm sorry, please don't kill me!");
		yield return lineBreak();
		Vars.playersMissionIsComplete  = true;
		yield return lineBreak();
		Vars.Score  = Vars.Score+500;
		yield break;
	}


}